### ISSUE TITLE
Adding an obvious link back to the repository

### ISSUE THREAD

**Issue by oalders** [tynovsky/cpan-tutorials#3]
Thanks very much for making this available.  When I was looking at the site, I didn't see an obvious link back to the repository.  Obviously I did eventually find it, but if it would be nice to see a prominent link.

This is a great idea and something we should probably link to from MetaCPAN.

**Comment by tynovsky** [comment]
Good idea, I'll add the link back so that it is also more obvious that everyone can contribute! :-)

I'd be honoured if this got a link from MetaCPAN.
